faqproject/faqproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("issuesapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faqproject/issuesapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "issuesapp"

urlpatterns = [
    path("", views.issues, name="main"),
    path(
        "create/",
        views.create_issue,
        name="create",
    ),
    path(
        "issue/<int:issue_id>",
        views.show_issue,
        name="issue",
    ),
    path(
        "edit/<int:issue_id>",
        views.edit_issue,
        name="edit",
    ),
    path(
        "delete/<int:issue_id>",
        views.delete_issue,
        name="delete",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

faqproject/issuesapp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Issue(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to="images", default="images/no_image.jpg")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolved = models.BooleanField(default=False)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

faqproject/issuesapp/forms.py
from django.forms import (
    ModelForm,
    CharField,
    SelectMultiple,
    TextInput,
    FileInput,
    ImageField,
    Textarea,
    MultipleChoiceField,
)

from .models import Issue, Tag


class IssueForm(ModelForm):
    title = CharField(
        max_length=100,
        min_length=5,
        required=True,
        widget=TextInput(
            attrs={"class": "form-control", "placeholder": "Sort name issue"}
        ),
    )
    description = CharField(
        min_length=10,
        required=True,
        widget=Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Description",
                "cols": "40",
                "style": "min-height: 300px",
            }
        ),
    )
    image = ImageField(
        required=False, widget=FileInput(attrs={"class": "form-control"})
    )

    tags = MultipleChoiceField(
        choices=Tag.objects.all().values_list("id", "name"),
        widget=SelectMultiple(attrs={"class": "form-control"}),
        required=True,  # You can set it to False if you prefer
    )

    class Meta:
        model = Issue
        fields = ["title", "description", "image", "tags"]

faqproject/issuesapp/views.py
from django.shortcuts import redirect, render

from .models import Issue, Tag

from .forms import IssueForm


# Create your views here.


def issues(request):
    issues = Issue.objects.all()
    return render(
        request, "issuesapp/main.html", context={"title": "Issues", "issues": issues}
    )


def create_issue(request):
    if request.method == "POST":
        form = IssueForm(request.POST, request.FILES, instance=Issue())

        if form.is_valid():
            issue = form.save(commit=False)
            id_tags = form.cleaned_data["tags"]
            for id_tag in id_tags:
                tag = Tag.objects.get(id=id_tag)
                issue.tag = tag
            issue.save()

            return redirect(to="issuesapp:main")
        return render(
            request,
            "issuesapp/create.html",
            context={
                "form": form,
            },
        )
    return render(
        request,
        "issuesapp/create.html",
        context={"form": IssueForm()},
    )


def show_issue(request, issue_id):
    issue = Issue.objects.get(id=issue_id)
    return render(request, "issuesapp/issue.html", context={"issue": issue})


def edit_issue(request, issue_id):
    issue = Issue.objects.get(id=issue_id)
    form = IssueForm(instance=issue)
    if request.method == "POST":
        form = IssueForm(request.POST, request.FILES, instance=issue)
        if form.is_valid():
            form.save()
            return redirect(to="issuesapp:main")
        return render(
            request, "issuesapp/edit_issue.html", context={"form": form, "issue": issue}
        )

    return render(
        request, "issuesapp/edit_issue.html", context={"form": form, "issue": issue}
    )


def delete_issue(request, issue_id):
    issue = Issue.objects.get(id=issue_id)
    issue.delete()
    return redirect(to="issuesapp:main")

faqproject/issuesapp/templates/issuesapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'issuesapp/styles.css' %}">
    <title>{{title}}</title>
</head>
<body>
    <div class="container-fluid text-center mt-3">
      <div class="row justify-content-between">
        <div class="col-2">
          <a href="{% url "issuesapp:main" %}"><h2>FAQ Canvas</h2></a>
        </div>
        <div class="col-2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "issuesapp:main" %}">Main</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "issuesapp:create" %}">Create</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  {% block content %}{% endblock content %}
</body>
</html>

faqproject/issuesapp/templates/issuesapp/create.html
{% extends "issuesapp/base.html" %}
{% block content %}
<form action="{% url 'issuesapp:create' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
    {% if form.error and form.non_field_errors %}
      <span class="alert alert-danger" role="alert">{{ form.non_field_errors }}</span>
    {% endif %}
  </div>
  <div class="container mb-3 mt-3 ms-2">
    {{ form.title }}
    <span>{{ form.error.title }}</span>
  </div>
  <div class="container mb-3 mt-3 ms-2">
    {{ form.description }}
    <span>{{ form.error.description }}</span>
  </div>
  <div class="container mb-3 mt-3 ms-2">
    {{ form.image }}
    <span>{{ form.error.image }}</span>
  </div >

  <div class="container mb-3 mt-3 ms-2">
    {{ form.tags }}
    {% if form.tags.errors %}
      <span>{{ form.tags.errors }}</span>
    {% endif %}
  </div>


  <div class="container mb-3 mt-3 ms-2">
    <button type="submit" class="btn btn-success">Send</button>
    <button type="reset" class="btn btn-danger">Reset</button>
  </div>
</form>
{% endblock content %}

faqproject/issuesapp/templates/issuesapp/edit_card.html
{% extends "issuesapp/base.html" %} {% block content %}
<form action="{%url 'issuesapp:edit'%}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
    {%if form.error and form.non_field_errors%}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {%endif%}
  </div>
  <div class="container mb-3 mt-3 ms-2">
    {{}} {{form.title}}
    <span>{{form.error.title}}</span>
  </div>
  <div class="container mb-3 mt-3 ms-2">{{ form.description}}<span>{{form.error.description}}</span></div>
  <div class="container mb-3 mt-3 ms-2">{{ form.image}}<span>{{form.error.image}}</span></div>
  <div class="container mb-3 mt-3 ms-2">
    <button type="submit" class="btn btn-success">Send</button>
    <button type="reset" class="btn btn-danger">Reset</button>
  </div>
</form>
{% endblock content %}

faqproject/issuesapp/templates/issuesapp/edit_issue.html
{% extends "issuesapp/base.html" %} {% block content %}
<form action="{%url 'issuesapp:edit' issue.id %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
    {%if form.error and form.non_field_errors%}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {%endif%}
  </div>
  <div class="container mb-3 mt-3 ms-2">
    {{issue.title}} {{form.title}}
    <span>{{form.error.title}}</span>
  </div>
  <div class="container mb-3 mt-3 ms-2">
    {{issue.description}} {{ form.description}}
    <span>{{form.error.description}}</span></div>
  <div class="container mb-3 mt-3 ms-2">{{ form.image}}<span>{{form.error.image}}</span></div>
  <div class="container mb-3 mt-3 ms-2">
    <button type="submit" class="btn btn-success">Send</button>
    <button type="reset" class="btn btn-danger">Reset</button>
  </div>
</form>
{% endblock content %}

faqproject/issuesapp/templates/issuesapp/issue.html
{% extends "issuesapp/base.html" %}{% block content %}

<div class="container">
  <h1>{{issue.title}}</h1>
  <p>{{issue.description}}</p>
  <p>{{issue.status}}</p>
  <p>Created: {{issue.created_at}}</p>
  <p>{{issue.tag}}</p>
  <img src="{{issue.image.url}}" alt=""   width="400"/>
</div>
<div class="container mb-3 mt-3 ms-2">
    <a href="{% url "issuesapp:edit" issue.id %}" class="btn btn-info">Change description</a>
    <a href="{% url "issuesapp:delete" issue.id %}" class="btn btn-danger">Delete</a>
</div>
{% endblock content %}

faqproject/issuesapp/templates/issuesapp/issues.html
{% extends "issuesapp/base.html" %} {% block content %} {% for issue in issues %}
<div class="container mt-3 ms-5">
  <div class="card">
    <a href="#" class="card-link"></a>
    <div class="card-body">
      <h5 class="card-title">{{issue.title}}</h5>
      <p class="card-text">{{issue.description}}</p>
    </div>
  </div>
</div>
{% endfor %} {% endblock content %}

faqproject/issuesapp/templates/issuesapp/main.html
{% extends "issuesapp/base.html" %} {% block content %} {% load static %} {% for issue in issues %}
<div class="container mt-3 ms-5 w-50">
  <div class="card">
    <a href="{% url "issuesapp:issue" issue.id %}" class="card-link"></a>
    <div class="card-body">
      <h5 class="card-title">{{issue.title}}</h5>
      <p class="card-text" style = "overflow: hidden;
      text-overflow: ellipsis;
      display: -webkit-box;
      -webkit-line-clamp: 2; /* Number of lines to show */
      -webkit-box-orient: vertical;">{{issue.description}}</p>
    </div>
  </div>
</div>
{% endfor %} {% endblock content %}